fix: upgraded to spring boot 3.4.1, fixed NoSuchMethodError: 'void org.springframework.web.method.ControllerAdviceBean' due to incompatible version of springdoc-openapi-starter-webmvc-ui